//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_master
    {
        public int am_id { get; set; }
        public Nullable<int> am_atype_id { get; set; }
        public Nullable<int> am_make_id { get; set; }
        public Nullable<int> am_ad_id { get; set; }
        public string am_model { get; set; }
        public string am_snumber { get; set; }
        public string am_myyear { get; set; }
        public DateTime am_pdate { get; set; }
        public string am_pdateStr
        {
            get
            {
                return am_pdate.ToString("yyyy-MM-dd");
            }
        }
        public string am_warranty { get; set; }
        public Nullable<System.DateTime> am_from { get; set; }
        public Nullable<System.DateTime> am_to { get; set; }
    
        public virtual Asset_def Asset_def { get; set; }
        public virtual Asset_type Asset_type { get; set; }
        public virtual vendor vendor { get; set; }
    }
}
