//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_order
    {
        public int pd_id { get; set; }
        public string pd_order_no { get; set; }
        public Nullable<int> pd_ad_id { get; set; }
        public Nullable<int> pd_type_id { get; set; }
        public Nullable<decimal> pd_qty { get; set; }
        public Nullable<int> pd_vendor_id { get; set; }
        public DateTime pd_date { get; set; }
        public string pd_dateStr
        {
            get
            {
                return pd_date.ToString("yyyy-MM-dd");
            }
        }

        public Nullable<DateTime> pd_ddate { get; set; }
        public string pd_ddateStr
        {
            get
            {
                return pd_ddate.ToString();
            }
        }
        public string pd_status { get; set; }
    
        public virtual Asset_def Asset_def { get; set; }
        public virtual Asset_type Asset_type { get; set; }
        public virtual vendor vendor { get; set; }
    }
}
